services:
  client:
    env_file: .env
    environment:
      - PORT_CLIENT=${PORT_CLIENT:-8080}
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    networks:
      - default
    volumes:
      - ./client:/client
    restart: unless-stopped
    expose:
      - "${PORT_CLIENT}"
  server:
    env_file: .env
    environment:
      - PORT_SERVER=${PORT_SERVER:-3000}
      - APP_USER=${APP_USER:-admin}
      - ADMIN_PWD=${ADMIN_PWD:-SECURE_PASSWORD}
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    networks:
      - default
    volumes:
      - ./server:/server
      - $HOME/.ssh:/home/node/.ssh
      - ./_config:/config
    restart: unless-stopped
    expose:
      - "${PORT_SERVER}"
  mariadb:
    env_file: .env
    build:
      context: ./mariadb/
      args:
        DB_NAME: $DB_NAME
        DB_NETWORK: $DB_NETWORK
        DB_USER: $DB_USER
        DB_PASS: $DB_PASS
    networks:
      - default
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
  proxy:
    env_file: .env
    environment:
      - FEDERATION=${FEDERATION:-localhost}
      - HTTP_PORT=${HTTP_PORT:-80}
    build:
      context: ./proxy/
    networks:
      - default
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
volumes:
  mysqldata:
