FROM node:18
RUN apt update && apt install -y zip
COPY _docker/entrypoint.dev.sh /entrypoint.sh
COPY _docker/zfsdom /usr/bin
RUN mkdir /server
RUN npm install -g serve
COPY _docker/build.sh /
ENTRYPOINT ["/entrypoint.sh"]
